export const LOGIN_ROUTE = 'login'
export const CURRENCIES_ROUTE = 'currencies'
export const LATEST_RATES_ROUTE = 'latest-rates'
export const CURRENCY_CONVERTER_ROUTE = 'currency-converter'
export const HISTORICAL_RATES_ROUTE = 'historical-rates'
